# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Collect Submissions

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f collector/requirements.txt ]; then pip install -r collector/requirements.txt; fi
    - name: Collect Submissions
      env:
        GROUP_ID: 11216
        BOJ_AUTO_LOGIN: ${{ secrets.BOJ_AUTO_LOGIN }}
        ONLINE_JUDGE: ${{ secrets.ONLINE_JUDGE }}
      run: |
        python collector/main.py
    - name: Commits
      
      run: |
        git config --local user.email "dalgors.deu[bot]@gmail.com"
        git config --local user.name "dalgors[bot]"
        git add submissions.json
        if [ -z "$(git status --porcelain)" ]; then echo "Nothing changed"; else git commit -m "[Bot] Update submissions"; fi
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: $ 
